replicaCount: 3

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    acme.cert-manager.io/http01-edit-in-place: "true"

  hosts:
    - host: dev1.oliaasem.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: nodejs-dev-tls
      hosts:
        - dev1.oliaasem.com